# Site settings
name: Abhinav Lakhani
email: 3398abhinav@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Python, Julia, C, Machine Learning, Deep Learning, Data Engineer, Agile, Pair Programming, Game/Mobile/Web/Software Developer, Mechatronics Engineer"
skills: "Computer Programmer in Gandhinagar, GJ (India)"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/abhinav-lakhani/
  - title: github
    url: https://github.com/abhinav3398
  - title: grab-cad
    url: https://grabcad.com/abhinav.lakhani-2

# Google Google Search Console:
# https://search.google.com/search-console/
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
